language: php
php:
  - '7.1'
install:
  - composer install
env:
  - DB_HOST=127.0.0.1 DB_PORT=123 DB_NAME=name DB_USER=user DB_PASSWORD=pw SENDGRID_API_KEY=add-key MAIL_RECIPIENT=me@example.com CORS_ALLOW_ORIGIN=https://your-client-url.com LOCALE=en SECRET=secret HTTP_PASSWORD=ADD
